fix bug with dictionary getting
Was getting an error saying:
File "/Users/xxx/atlassian/atlassian-python-api/examples/confluence/confluence_check_unknown_attachment_error.py", line 50, in <module>
    print("Start review {} space".format(space["key"]))
TypeError: string indices must be integers

the space in the space_list was returning 
{'results': [{'id': 1146881, 'key': 'AR',...

.. instead of just the list of spaces, so this circumvents the error.